apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-demo
  labels:
    app: html-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-demo
  template:
    metadata:
      labels:
        app: html-demo
    spec:
      containers:
        - name: html-demo
          image: deepaksingh20i1/html-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "250m"
              memory: "128Mi"
