apiVersion: v1
kind: Service
metadata:
  name: html-demo
  labels:
    app: html-demo
spec:
  type: NodePort
  selector:
    app: html-demo
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080
