apiVersion: v1
kind: Service
metadata:
  name: deepak-service
  labels:
    app: deepak-app
spec:
  selector:
    app: deepak-app
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
